#! /bin/php
<?php

// File:	emp_make_test
// Author:	walton@acm.org
// Date:	Wed Nov 20 02:17:56 EST 2019

$epm_data = getcwd() . '/data';
echo "epm_data set to $epm_data\n";

$_SESSION = [ 'userid' => 1, 'problem' => 'prob' ];

if ( ! file_exists ( './data/users/user1/prob' ) )
    mkdir ( './data/users/user1/prob', 0750, true );

include ( '../src/include/epm_make.php' );

function check ( $expression, $value )
{
    $result;
    eval ( "\$result = ($expression);" );
    if ( $result != $value )
    {
        $v1 = json_encode ( $result );
        $v2 = json_encode ( $value );
        echo "FAILED: $expression\n";
	echo "    $v1 != $v2\n";
    }
}

check ( '["A" => 0, "B" => 1]', ["B" => 1, "A" => 0] );

check ( 'template_match
              ( "tv", "tv.cc", "PPPP.cc" )',
	 ["PPPP" => "tv"] );
check ( 'template_match
              ( "tv", "00-001-tv.in",
	        "XXXX-YYYY-PPPP.in" )',
	 ["XXXX" => "00","YYYY" => "001",
	                 "PPPP" => "tv"] );
check ( 'template_match // tvxin, NOT tv.in
              ( "tv", "00-001-tvxin",
	        "XXXX-YYYY-PPPP.in" )',
	 false );

check ( 'substitute_match ( "XXXX-YYYY-PPPP.in",
           ["PPPP" => "tv", "XXXX" => "00",
	                    "YYYY" => "001"] )',
	 '00-001-tv.in' );
check ( 'substitute_match (
           ["X" => "XXXX/YYYY",
	    "O" => ["M" => "PPPP99", "N" => 88],
	    "Z" => "FOOBAT"],
           ["PPPP" => "tv", "XXXX" => "00",
	                    "YYYY" => "001"] )',
	 ["X" => "00/001",
	  "O" => ["M" => "tv99","N" => 88],
	  "Z" => "FOOBAT"] );

$epm_data = getcwd();

?>
