#!/bin/bash

D=`date -r ../src/$1.cc +'%D %T'`
../src/$1 -doc | \
    enscript \
	-2r \
	-F Courier-Bold12 \
	-f Courier10 \
	--margins=48:48:: \
	-b "$1|$D|\$% of \$=" \
	-p - | \
    ps2pdf - $1.pdf



