
epm_user:	epm_user.tex
	pdflatex -record -interaction nonstopmode \
	         -no-shell-escape epm_user.tex

epm_admin:	epm_admin.tex
	pdflatex -record -interaction nonstopmode \
	         -no-shell-escape epm_admin.tex
