epm_user:	epm_user.tex
	pdflatex -record -interaction nonstopmode \
	         -no-shell-escape epm_user.tex

epm_design:	epm_design.tex
	pdflatex -record -interaction nonstopmode \
	         -no-shell-escape epm_design.tex
